### PR TITLE
Fix svn checkout .Digester class not fount

### PR DESCRIPTION
**Pull request by zhuch-h**
Signed-off-by: 胡卓超 <849085386@qq.com>

### CODE REVIEW

**Comment by zhuch-h** [comment]
fix #89

**Comment by LinuxSuRen** [comment]
Sorry that I missed this PR. I'm wondering if you have built this by yourself. Please feel free to give me an image if it's.

**Comment by chilianyi** [comment]
截屏2023-02-20 19 42 09

when upgrade subversion plugin, the other two are also upgraded, version is not the same as the pr 

@zhuch-h please check again about the pr, and upload an svn succeeded image.

**Comment by yudong2015** [comment]
repeate #89

**Pull request closed without merging**
