### PR TITLE
Bump base Jenkins to 2.319.3

### PR DESCRIPTION
**Pull request by JohnNiang**
### What this PR dose / Why we need it

Bump base Jenkins to 2.319.3 according to https://www.jenkins.io/changelog-stable/#v2.319.3.

Something should be noticed at https://www.jenkins.io/doc/upgrade-guide/2.319/#upgrading-to-jenkins-lts-2-319-3.

/kind dependency

### CODE REVIEW

**Comment by JohnNiang** [comment]
/hold
Don't merge Util KubeSphere v3.3 release.

**Review by chilianyi — APPROVED** [review]

**Comment by chilianyi** [comment]
hi， @JohnNiang  ，I found there are lots of cve after trivy scan

https://github.com/kubesphere/ks-jenkins/actions/runs/4299097329/jobs/7493947531

So the pr check will not succeed, do you know how to fix it ?

**Comment by JohnNiang** [comment]
> hi， @JohnNiang ，I found there are lots of cve after trivy scan
> 
> https://github.com/kubesphere/ks-jenkins/actions/runs/4299097329/jobs/7493947531
> 
> So the pr check will not succeed, do you know how to fix it ?

I have no idea about how to fix these CVEs. You could keep the plugin up to date.

**Pull request merged**
