### PR TITLE
Add Prometheus plugin in formula.yaml

### PR DESCRIPTION
**Pull request by JohnNiang**
Add Prometheus plugin for preparing jenkins monitoring. Please follow <https://github.com/kubesphere/kubesphere/issues/3814>.

There is a convenient docker image: `johnniang/ks-jenkins:jenkins-monitoring` for test.

/kind feature
/area devops

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
Please fix the failed status.

**Comment by JohnNiang** [comment]
> Please fix the failed status.

All commits are signed off by `git rebase --sign-off HEAD~6`.

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
